### ISSUE TITLE
[功能建议] 默认的 menu

### ISSUE THREAD

**Issue by a-wing** [f-dong/hexo-theme-minimalism#24]
**功能概述**
请提供这个功能应该是什么样的

目前主题的配置，默认的 menu 部分。

```yaml
menu:
  Index:
    url: /
    External: false
    name: 首页
  Tags:
    url: /tags
    External: false
    name: 标签
  Archives:
    url: /archives
    External: false
    name: 归档
  About:
    url: /about
    External: false
    name: 关于
```

但实际上如果使用 `_config.minimalism.yml` 进行覆盖的化

比如这样：

```yaml
menu:
  Index:
    url: /
    External: false
    name: 首页
  Tags:
    url: /tags/
    External: false
    name: 标签
  Equipment:
    url: /equipment/
    External: false
    name: 装备
  Projects:
    url: /projects/
    External: false
    name: 作品
  Archives:
    url: /archives/
    External: false
    name: 归档
  About:
    url: /about/
    External: false
    name: 关于
```

但最终结果是这样的：

```yaml
menu:
  Index:
    url: /
    External: false
    name: 首页
  Tags:
    url: /tags
    External: false
    name: 标签
  Archives:
    url: /archives
    External: false
    name: 归档
  About:
    url: /about
    External: false
    name: 关于
  Equipment:
    url: /equipment/
    External: false
    name: 装备
  Projects:
    url: /projects/
    External: false
    name: 作品
```

如果使用 npm 安装的化，实际上并没有办法去改变 menu 的顺序。hexo 会把两个 `_config.yml` 进行合并。甚至不能去掉已经存在的按钮。建议默认配置里面把 menu 留空

* * *

BTW: 用 Map 来做有顺序的配置这在语法上并不严格。建议使用 Array

例如这样：

```yaml
menu:
 -
    url: /
    External: false
    name: 首页
 -
    url: /tags
    External: false
    name: 标签
 -
    url: /archives
    External: false
    name: 归档
 -
    url: /about
    External: false
    name: 关于
```
