### ISSUE TITLE
开启gitalk后，评论框未出现

### ISSUE THREAD

**Issue by yangqun-git** [f-dong/hexo-theme-minimalism#3]
gitalk:
  enable: true
  clientId: xxx
  clientSecret: xxxx
  repository: xxxxx
  owner: xxx
  createIssueManually: false, # 如果当前页面没有相应的 isssue 且登录的用户属于 admin，则会自动创建 issue。如果设置为 true，则显示一个初始化页面，创建 issue 需要点击 init 按钮。

如上设置为true，其它配置项也如实填写后未出现期待的评论框。

环境是master分支最新代码。

**Comment by f-dong** [comment]
> gitalk: enable: true clientId: xxx clientSecret: xxxx repository: xxxxx owner: xxx createIssueManually: false, # 如果当前页面没有相应的 isssue 且登录的用户属于 admin，则会自动创建 issue。如果设置为 true，则显示一个初始化页面，创建 issue 需要点击 init 按钮。
> 
> 如上设置为true，其它配置项也如实填写后未出现期待的评论框。
> 
> 环境是master分支最新代码。

已经复现了，明天上午会修复，修复后会在此 issues 内回复

**Comment by f-dong** [comment]
已修复，原因是在默认配置文件 `false` 多余了一个逗号，可以修改配置文件如下，或者拉取最新 master 代码并覆盖原有文件

```yml
gitalk:
  enable: true
  clientId: xxx
  clientSecret: xxxx
  repository: xxxxx
  owner: xxx
  createIssueManually: false # 如果当前页面没有相应的 isssue 且登录的用户属于 admin，则会自动创建 issue。如果设置为 true，则显示一个初始化页面，创建 issue 需要点击 init 按钮。
```
