### ISSUE TITLE
hide为true后，分页展示错误

### ISSUE THREAD

**Issue by yangqun-git** [f-dong/hexo-theme-minimalism#6]
设置hide为true后，文章会隐藏，但是仍然被记入分页的total里。如: 本来设置的每页展示16条，结果首页每页展示不够16条就下一页了。

**Comment by f-dong** [comment]
这个真的没什么办法了，分页是 `hexo` 提供的，实现一套独立的分页有点困难，如果有好的想法可以提交 PR

**Comment by yangqun-git** [comment]
怎么在post-list.ejs中获取全站所有文章？我首页直接不分页了，就放最新的几条文章

**Comment by yangqun-git** [comment]
> 怎么在post-list.ejs中获取全站所有文章？我首页直接不分页了，就放最新的几条文章

并按时间倒序的

**Comment by f-dong** [comment]
> 怎么在post-list.ejs中获取全站所有文章？我首页直接不分页了，就放最新的几条文章

这个很简单呀，在 hexo 根目录修改 `_config.yml` 文件中的 `index_generator.per_page` 为 0 或无限大的数字即可

```yml
# 首页设置
# path: 博客根目录路径，(默认值='’)
# per_page: 每页显示的帖子。(0=禁用分页)
# order_by: 文章的顺序。(默认按日期降序排序)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
```

**Comment by yangqun-git** [comment]
设置为0则首页展示了所有文章，我只是想首页展示最新的几条。

**Comment by f-dong** [comment]
> 设置为0则首页展示了所有文章，我只是想首页展示最新的几条。

暂无法做到，你可以自定义首页实现

**Comment by yangqun-git** [comment]
是的，我正是想自定义首页，奈何前端水平有限，所以问下在您当前写的这个文章列表页面里，我该如何获取当前所有文章？
![image](https://user-images.githubusercontent.com/34759396/213110485-8904702c-af8b-431c-ad3f-3a2cc5d8a715.png)
在这里如何获取站内所有文章，我好遍历出几条最新的展示，就不分页了。

**Comment by f-dong** [comment]
> 是的，我正是想自定义首页，奈何前端水平有限，所以问下在您当前写的这个文章列表页面里，我该如何获取当前所有文章？在这里如何获取站内所有文章，我好遍历出几条最新的展示，就不分页了。

前文已经说明了呀！修改分页参数后这里就是全部的文章

> 这个很简单呀，在 hexo 根目录修改 `_config.yml` 文件中的 `index_generator.per_page` 为 0 或无限大的数字即可

```yml
# 首页设置
# path: 博客根目录路径，(默认值='’)
# per_page: 每页显示的帖子。(0=禁用分页)
# order_by: 文章的顺序。(默认按日期降序排序)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
```
