### ISSUE TITLE
[BUG]归档页面不能分页，只能显示一部分文章

### ISSUE THREAD

**Issue by li199-code** [f-dong/hexo-theme-minimalism#9]
config.yml
```
menu:
  Index:
    url: /
    External: false
    name: Home
  Tags:
    url: /tags
    External: false
    name: Tags
  Categories:
    url: /categories
    External: false
    name: Categories
  Archives:
    url: /archives
    External: false
    name: Archives
  About:
    url: /about
    External: false
    name: About

# 深色主题
dark_theme:
  enable: true

# 联系方式
contact:
  github: "https://github.com/li199-code"
  twitter:
  weibo:
  zhihu:
  facebook:
  mail: ""

# 是否显示封面图片
showFeatureImage: true

# 首页头像图片
avatar: /images/avatar.png

# 谷歌统计 跟踪 ID
ga:

# 百度统计 The baidu web analytics
baidu_tongji:

# Gittalk 评论组件
# See: https://github.com/gitalk/gitalk/
gitalk:
  enable: false
  clientId:
  clientSecret:
  repository: # 仓库名
  owner: # 仓库所有者
  createIssueManually: false # 如果当前页面没有相应的 isssue 且登录的用户属于 admin，则会自动创建 issue。如果设置为 true，则显示一个初始化页面，创建 issue 需要点击 init 按钮。

# 是否使用 bootcdn
use_bootcdn: false

# 底部链接
bottom_link:
  rss:
    url:
    text: RSS
    class: rss
  icp:
    url: # beian.miit.gov.cn
    text: # 沪ICP备 09007032号-1
    class: icp

# 底部显示来源信息
bottom_source:
  enable: true

# 脚注
footnote:
  enable: true # 是否开启脚注解析
  ignoreCodeBlock: false # 是否忽略代码块中的脚注

# 图片配置
image:
  lazyload_enable: false # 图片懒加载

```
